server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    host: 47.101.42.50
    port: 3306
    database: coupon
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: root
    password: 123456
    DriverClassName: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 106.14.190.167
    port: 5672
    username: test
    password: onlyTest
    publisher-confirms: true #消息发到交换机确认机制，是否确认回调
    publisher-returns: true #消息发到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual

  redis:
    database: 0
    host: 47.101.42.50
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 1000

  logging:
    config: classpath:logback.xml







